routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PagesController@index')->name('home');

Route::get('/about', 'PagesController@about')->name('about');

Route::get('/services', 'PagesController@services')->name('services');

Route::resource('posts', 'PostsController');

Route::get('post_index', 'PostsController@index')->name('post_index');

// Route::get('posts/{post}/comment', 'CommentsController@store')->name('create.comment');

Route::resource('comments', 'CommentsController');
// Route::post('comments/{id}', 'CommentsController@store');

/*Route::get('/users/{user}/{id}', function($user, $id){
    return 'user  '. $user .'  has id of ' .$id;
});*/

Auth::routes();

Route::get('/dashboard', 'DashboardController@index');

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('title')
    Dashboard
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <a class="btn btn-primary" href="{{ route('posts.create') }}">Create Post</a>
                    <hr>
                        <h3>Your Blog Posts</h3>
                        @if(count($posts) > 0)
                    <table class="table table-striped">
                        <tr>
                            <th>Title</th>
                            <th></th>
                            <th></th>
                        </tr>
                        @foreach ($posts as $post)
                        <tr>
                                <td>{{$post->title}}</td>
                                <td><a href="posts/{{$post->id}}/edit" class="btn btn-outline-secondary">Edit</a></td>
                                <td>
                                        {!! Form::open(['action' => ['PostsController@destroy', $post->id], 'method' => 'POST', 'class' => 'float-right', 'onsubmit' => 'return confirm("Delete Post ?")']) !!}
                                        {!! Form::hidden('_method', 'DELETE') !!}
                                        {!! Form::submit('Delete', ['class' => 'btn-danger btn float-right']) !!}
                                </td>
                            </tr>
                        @endforeach
                        </table>
                        @else
                            <p>You Have no posts yet .. write some </p>
                        @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection